/*	Справочник Функций	*/

CREATE TABLE FOTF.T_SPR_FUNK
(
		FUNC_ID INT NOT NULL		-- Ид функуии
	,	DESCRIPTION VARCHAR(MAX)	-- Расшифровка
 CONSTRAINT PK_FUNC_ID PRIMARY KEY CLUSTERED 
(
	FUNC_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/*	Справочник рекласса	*/

CREATE TABLE FOTF.T_SPR_RECL
(
		RECL_ID INT NOT NULL		-- ИД рекласса
	,	DESCRIPTION VARCHAR(MAX)	-- Расшифровка
 CONSTRAINT PK_RECL_ID PRIMARY KEY CLUSTERED 
(
	RECL_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/*	Справочник статей	*/

CREATE TABLE FOTF.T_SPR_STAT
(
		STAT_ID1 INT NOT NULL	-- ИД статьи 1 уровня статьи
	,	STAT1 VARCHAR(MAX)		-- Расшифровка 1 уровня статьи
	,	STAT_ID2 INT NOT NULL	-- ИД статьи 2 уровня статьи
	,	STAT2 VARCHAR(MAX)		-- Расшифровка 4 уровня статьи
	,	STAT_ID3 INT NOT NULL	-- ИД статьи 3 уровня статьи
	,	STAT3 VARCHAR(MAX)		-- Расшифровка 3 уровня статьи
	,	STAT_ID4 INT NOT NULL	-- ИД статьи 4 уровня статьи
	,	STAT4 VARCHAR(MAX)		-- Расшифровка 3 уровня статьи
 CONSTRAINT PK_STAT_ID PRIMARY KEY CLUSTERED 
(
	STAT_ID1 ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/*	Справочник видов расчетов
*/
CREATE TABLE FOTF.T_SPR_COSTS
(
		COST_ITEM_ID INT NOT NULL	-- ИД Вида расчета
	,	VID VARCHAR(MAX)			-- Расшифровка
	,	STAT_ID1 INT				-- Принадлежность виа расчета к статье
CONSTRAINT PK_COST_ITEM_ID PRIMARY KEY CLUSTERED 
(
	COST_ITEM_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
;

ALTER TABLE FOTF.T_SPR_COSTS ADD FUNC_ID INT --Добавим принадлежность функции

/*	Добавление ключа вторичного по статьям
*/
ALTER TABLE FOTF.T_SPR_COSTS
ADD CONSTRAINT FK_STAT_ID1 FOREIGN KEY (STAT_ID1)
REFERENCES FOTF.T_SPR_STAT (STAT_ID1)
;
/*	Добавление ключа вторичного по функции
*/
ALTER TABLE FOTF.T_SPR_COSTS
ADD CONSTRAINT FK_FUNC_ID FOREIGN KEY (FUNC_ID)
REFERENCES FOTF.T_SPR_FUNK (FUNC_ID)
;

/* Добавление справочника должностей
*/
CREATE TABLE FOTF.T_SPR_JOB_TITLE
(
		JOB_TITLE_ID INT NOT NULL 
	,	JOB VARCHAR(MAX)
CONSTRAINT PK_JOB_TITLE_ID PRIMARY KEY CLUSTERED 
(
	JOB_TITLE_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/* Добавление справочника Периода
*/
CREATE TABLE FOTF.T_SPR_MONTH
(
		MONTH_ID INT NOT NULL	--Номер месяца
	,	MONTH_NAME VARCHAR(MAX)	--Месяц
CONSTRAINT PK_MONTH_ID PRIMARY KEY CLUSTERED 
(
	MONTH_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

/*	Справочник подразделений ЦФО
*/
CREATE TABLE FOTF.T_SPR_DIV_CFO
(
		CFO_ID INT NOT NULL	-- ИД подразделения
	,	OBJCT_ID INT NOT NULL -- ИД Объекта
	,	GROUP_ID INT NOT NULL -- ИД Группа Объекта
	,	GROUP_NAME VARCHAR(MAX) NOT NULL -- Группа Объекта Расшифровка
	,	LVL1_NAME VARCHAR(MAX) NOT NULL -- Подразделение 1 уровня
	,	LVL2_NAME VARCHAR(MAX) NOT NULL -- Подразделение 2 уровня
	,	LVL3_NAME VARCHAR(MAX) NOT NULL -- Подразделение 3 уровня
	,	LVL4_NAME VARCHAR(MAX) NOT NULL -- Подразделение 4 уровня
	,	LVL5_NAME VARCHAR(MAX) NOT NULL -- Подразделение 5 уровня
	,	CODE	VARCHAR(9)	NOT NULL	-- Текстовое поле КИС
CONSTRAINT PK_CFO_ID PRIMARY KEY CLUSTERED 
(
	CFO_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/*	Справочник подразделений ЗУП
*/
CREATE TABLE FOTF.T_SPR_STAFF_DIV
(
		STAFF_DIV_ID INT NOT NULL	-- ИД подразделения
	,	ORG_NAME	VARCHAR(MAX) NOT NULL -- Группа Объекта Расшифровка
	,	LVL1_NAME	VARCHAR(MAX) NOT NULL -- Подразделение 1 уровня
	,	LVL2_NAME	VARCHAR(MAX) NOT NULL -- Подразделение 2 уровня
	,	LVL3_NAME	VARCHAR(MAX) NOT NULL -- Подразделение 3 уровня
	,	LVL4_NAME	VARCHAR(MAX) NOT NULL -- Подразделение 4 уровня
	,	LVL5_NAME	VARCHAR(MAX) NOT NULL -- Подразделение 5 уровня
	,	CODE		VARCHAR(9)	NOT NULL	-- Текстовое поле Кодировка ЗУП
CONSTRAINT PK_STAFF_DIV_ID PRIMARY KEY CLUSTERED 
(
	STAFF_DIV_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


/*	Справочник исчтоников
*/
CREATE TABLE FOTF.T_SPR_SOURCE
(
		IST_ID INT NOT NULL	-- ИД исчтоника
	,	IST_NAME	VARCHAR(MAX) NOT NULL -- Расшифровка Источника
	,	GRP_ID		INT NOT NULL -- ИД Группы
	,	GRP_NAME	VARCHAR(MAX) NOT NULL -- Расшифровка группы
CONSTRAINT PK_IST_ID PRIMARY KEY CLUSTERED 
(
	IST_ID ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



/*	Табличка
*/
CREATE TABLE FOTF.T_SOURCE_MAIN
(
		MONTH_ID INT NOT NULL
	,	CFO_ID INT NOT NULL
	,	CFO_ID2 INT NOT NULL
	,	STAFF_DIV_ID INT NOT NULL
	,	JOB_TITLE_ID INT NOT NULL
	,	JOB_TITLE_NAME VARCHAR(MAX) NULL
	,	CAPITALIZ SMALLINT NOT NULL 
	,	ATTREBUTE_ID	SMALLINT
	,	SUMMA	FLOAT	NULL
	,	CAPEX	FLOAT	NULL
 )
 ;

 ALTER TABLE FOTF.T_SOURCE_MAIN ADD IST INT
 ALTER TABLE FOTF.T_SOURCE_MAIN ADD COST_ITEM_ID INT

 ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_MONTH_ID FOREIGN KEY (MONTH_ID)
REFERENCES FOTF.T_SPR_MONTH (MONTH_ID)
;

 ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_CFO_ID FOREIGN KEY (CFO_ID)
REFERENCES FOTF.T_SPR_DIV_CFO (CFO_ID)
;

 ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_CFO_ID2 FOREIGN KEY (CFO_ID2)
REFERENCES FOTF.T_SPR_DIV_CFO (CFO_ID)
;

ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_STAFF_DIV_ID FOREIGN KEY (STAFF_DIV_ID)
REFERENCES FOTF.T_SPR_STAFF_DIV (STAFF_DIV_ID)
;

ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_JOB_TITLE_ID FOREIGN KEY (JOB_TITLE_ID)
REFERENCES FOTF.T_SPR_JOB_TITLE (JOB_TITLE_ID)
;

ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_IST_ID FOREIGN KEY (IST)
REFERENCES FOTF.T_SPR_SOURCE (IST_ID)
;

ALTER TABLE FOTF.T_SOURCE_MAIN
ADD CONSTRAINT FK_COST_ITEM_ID FOREIGN KEY (COST_ITEM_ID)
REFERENCES FOTF.T_SPR_COSTS (COST_ITEM_ID)
;

SELECT * FROM FOTF.T_SPR_COSTS 

CREATE VIEW FOTF.V_SPR_CAPITALIZED
AS
SELECT CAST(0 AS INT) CAPITALIZ_ID	, CAST('Не капитализация' AS VARCHAR(16)) AS DESCRIPTION
UNION ALL
SELECT CAST(1 AS INT)				, CAST('Капитализация' AS VARCHAR(16))
;

